import React, { useContext, useEffect, useState } from 'react'
import tw from '../styles/tailwind'

import { Loading } from '../components'

import { MessageContext } from '../contexts/message'
import { OverlayContext } from '../contexts/overlay'
import getContractEffect from '../effects/getContractEffect'
import { account } from '../utils/account'
import { getOffer } from '../utils/offer'
import { DisputeLostBuyer } from './disputeResults/DisputeLostBuyer'
import { DisputeLostSeller } from './disputeResults/DisputeLostSeller'
import { DisputeWonBuyer } from './disputeResults/DisputeWonBuyer'
import { DisputeWonSeller } from './disputeResults/DisputeWonSeller'
import { NonDispute } from './disputeResults/NonDispute'
import { getChat, saveChat } from '../utils/chat'
import { endDisputeSystemMessages } from '../utils/chat/createDisputeSystemMessages'
import i18n from '../utils/i18n'
import { useNavigation } from '../hooks'

type DisputeResultProps = {
  contractId: Contract['id']
}

export const DisputeResult = ({ contractId }: DisputeResultProps) => {
  const navigation = useNavigation()
  const [, updateOverlay] = useContext(OverlayContext)
  const [, updateMessage] = useContext(MessageContext)

  const [contract, setContract] = useState<Contract>()
  const [offer, setOffer] = useState<BuyOffer | SellOffer>()

  const [view, setView] = useState<'seller' | 'buyer' | ''>('')
  const [hasWinner, setHasWinner] = useState(false)
  const [isWinner, setIsWinner] = useState(false)

  useEffect(
    getContractEffect({
      contractId,
      onSuccess: async (result) => {
        const newView = result.seller.id === account.publicKey ? 'seller' : 'buyer'
        setContract(result)
        setOffer(getOffer(result.id.split('-')[newView === 'seller' ? 0 : 1]) as BuyOffer | SellOffer)

        setView(newView)
        setHasWinner(!!result.disputeWinner)
        setIsWinner(newView === result.disputeWinner)
        const chat = getChat(contractId)
        const autogeneratedMessages = endDisputeSystemMessages(chat.id, result)
        saveChat(contractId, {
          messages: autogeneratedMessages,
        })
      },
      onError: (err) => {
        updateMessage({
          msgKey: err.error || 'GENERAL_ERROR',
          level: 'ERROR',
          action: () => navigation.navigate('contact'),
          actionLabel: i18n('contactUs'),
          actionIcon: 'mail',
        })
        updateOverlay({ visible: false })
        return navigation.navigate('contract', { contractId })
      },
    }),
    [contractId],
  )

  const goToContract = () => {
    navigation.navigate('contract', { contractId })
    updateOverlay({ visible: false })
  }

  return !view || !contract || !offer ? (
    <Loading color={tw`text-white-1`.color} />
  ) : !hasWinner ? (
    <NonDispute {...{ contract, navigate: goToContract }} />
  ) : view === 'seller' ? (
    isWinner ? (
      <DisputeWonSeller {...{ contract, offer: offer as SellOffer, navigate: goToContract }} />
    ) : (
      <DisputeLostSeller {...{ contract, navigate: goToContract }} />
    )
  ) : isWinner ? (
    <DisputeWonBuyer {...{ contract, navigate: goToContract }} />
  ) : (
    <DisputeLostBuyer {...{ contract, navigate: goToContract }} />
  )
}
