export const paymentDataInfoFields: PaymentDataField[] = [
  "accountNumber",
  "bankAccountNumber",
  "bankBranch",
  "bankName",
  "bankNumber",
  "beneficiary",
  "beneficiaryAddress",
  "bic",
  "bsbNumber",
  "cedulaID",
  "DNI",
  "email",
  "iban",
  "lnurlAddress",
  "name",
  "nameTag",
  "phone",
  "pixAlias",
  "postePayNumber",
  "receiveAddress",
  "reference",
  "routingDetails",
  "RUT",
  "steamFriendCode",
  "ukBankAccount",
  "ukSortCode",
  "userId",
  "userName",
  "wallet",
];

export type PaymentDetailInfo = Partial<
  Record<PaymentDataField, Record<string, string>>
>;
