export const PaymentDataInfoFields: PaymentDataField[] = [
  "userName",
  "email",
  "phone",
  "reference",
  "beneficiary",
  "iban",
  "bic",
  "wallet",
  "accountNumber",
  "ukBankAccount",
  "ukSortCode",
  "receiveAddress",
  "lnurlAddress",
  "pixAlias",
  "postePayNumber",
  "edrpou",
  "clabe",
  "bankName",
  "steamFriendCode",
  "upiTag",
  "trSortCode",
  "cardNumber",
  "physicalAddress",
  "mobileNetwork",
  "bankCode",
  "brSortCode",
  "cpf",
  "cedulaIdentidad",
  "countryField",
  "bankBranch",
  "rutNumber",
  "dniNumber",
  "abitabAgent",
  "payeerNumber",
  "perfectMoneyNumber",
];

export type PaymentDetailInfo = Partial<
  Record<PaymentDataField, Record<string, string>>
>;
