import { IconType } from '../../assets/icons'

export const iconMap: Record<string, IconType> = {
  'contract.warning.highFee': 'helpCircle',
  'contract.warning.lowFee': 'helpCircle',
  'notification.contract.buyer.paymentReminderOneHour': 'watch',
  'notification.contract.buyer.paymentReminderSixHours': 'watch',
  'notification.offer.outsideRange': 'trendingUp',
  'referrals.codeNotFound': 'search',
  'referrals.myFavoriteCode': 'smile',
  CANNOT_DOUBLEMATCH: 'shuffle',
  CREATE_ESCROW_ERROR: 'xCircle',
  CRITICAL_UPDATE_AVAILABLE: 'alertOctagon',
  DAILY_TRADING_LIMIT_REACHED: 'trendingUp',
  EMPTY_RESPONSE: 'noNetwork',
  ERROR_SAVE_ACCOUNT: 'userX',
  FORM_INVALID: 'alertCircle',
  GENERAL_ERROR: 'peachSettings',
  INTERNAL_SERVER_ERROR: 'peachSettings',
  INVALID_INPUT: 'xCircle',
  INVALID_OUTPUT: 'xCircle',
  NAVIGATION_INIT_ERROR: 'map',
  NETWORK_ERROR: 'noNetwork',
  NOT_FOUND: 'map',
  OFFER_TAKEN: 'shuffle',
  PAYMENT_DATA_MISSING: 'creditCard',
  PAYMENTDATA_ENCRYPTION_FAILED: 'crossOutlined',
  POST_OFFER_ERROR: 'noNetwork',
  RETURN_ADDRESS_MISMATCH: 'rotateCounterClockwise',
  SERVICE_UNAVAILABLE: 'activity',
  TOO_MANY_REQUESTS: 'trendingUp',
  UNAUTHORIZED: 'eyeOff',
  UNAVAILABLE_FOR_LEGAL_REASONS: 'flag',
  UPDATE_AVAILABLE: 'chevronsUp',
  WRONG_PASSWORD: 'shield',
  YEARLY_TRADING_LIMIT_REACHED: 'trendingUp',
}
