import { getSellerStatusText } from './getSellerStatusText'

describe('getSellerStatusText', () => {
  it.todo('should return the correct status if the buyer canceled and republish is available')
  it.todo('should return the correct status if the buyer canceled and republish is not available')
  it.todo('should return the correct status if the buyer canceled and offer was republished')
  it.todo('should return the correct status if the buyer canceled and offer was refunded')
  it.todo('should return the correct status if the seller canceled a cash trade')
  it.todo('should return the correct status if the trade was canceled collaboratively and republish is available')
  it.todo('should return the correct status if the trade was canceled collaboratively and republish is not available')
  it.todo('should return the correct status if the trade was canceled collaboratively and offer was republished')
  it.todo('should return the correct status if the trade was canceled collaboratively and offer was refunded')
  it.todo('should return the correct status if payment was too late and seller can cancel or give more time')
  it.todo('should return the correct status if payment was too late and republish is available')
  it.todo('should return the correct status if payment was too late and republish is not available')
  it.todo('should return the correct status if payment was too late and offer was republished')
  it.todo('should return the correct status if payment was too late and offer was refunded')
  it.todo('should return the correct status if seller won the dispute and republish is available')
  it.todo('should return the correct status if seller won the dispute and republish is not available')
  it.todo('should return the correct status if seller won the dispute and offer was republished')
  it.todo('should return the correct status if seller won the dispute and offer was refunded')
  it.todo('should return the correct status if seller lost the dispute and has not released the funds')
  it.todo('should return the correct status if seller lost the dispute and has released the funds')
})
