const map: Record<Currency, PaymentMethodCountry[]> = {
  EUR: ["DE", "FR", "IT", "ES", "NL"],
  CHF: ["CH"],
  GBP: ["GB", "UK"],
  SEK: ["SE"],
  USD: ["US"],
  DKK: ["DK"],
  BGN: ["BG"],
  CZK: ["CZ"],
  HUF: ["HU"],
  PLN: ["PL"],
  RON: ["RO"],
  ISK: [],
  NOK: ["NO"],
  USDT: [],
  SAT: [],
  TRY: ["TR"],
  ARS: ["AR"],
  COP: [],
  PEN: [],
  MXN: ["MX"],
  CLP: [],
  XOF: [],
  NGN: ["NG"],
  CDF: [],
  CRC: [],
  BRL: ["BR"],
  BTC: [],
  GTQ: [],
  ZAR: ["ZA"],
  KES: [],
  GHS: [],
  UAH: [],
  XAU: [],
  RUB: ["RU"],
  BOB: [],
  CUP: [],
  DOP: [],
  HNL: [],
  NIO: [],
  PAB: [],
  VES: [],
  VEF: [],
  UYU: [],
  PYG: [],
  TZS: [],
  INR: [],
  UZS: [],
  RSD: [],
  KZT: [],
  KWD: [],
  ILS: [],
  NZD: [],
  PHP: [],
  EGP: [],
  CNY: ["CN"],
  JPY: ["JP"],
  AUD: ["AU"],
  IDR: ["ID"],
  VND: ["VN"],
  MAD: ["MA"],
  RWF: [],
  XAF: [],
  MGA: [],
  GNF: [],
};

export const countrySupportsCurrency =
  (currency: Currency) => (country: PaymentMethodCountry) =>
    map[currency].includes(country);
