import { raiseDispute } from '../../../utils/peachAPI'
import { signAndEncrypt } from '../../../utils/pgp'
import { PEACHPGPPUBLICKEY } from '../../../constants'
import { account } from '../../../utils/account'
import { getChat, saveChat } from '../../../utils/chat'
import { initDisputeSystemMessages } from '../../../utils/chat/createDisputeSystemMessages'
import { error } from '../../../utils/log'

export const submitRaiseDispute = async (
  contract: Contract | undefined,
  reason: DisputeReason,
  email?: string,
  message?: string,
) => {
  if (!contract || !contract.symmetricKey) return false
  const { encrypted: symmetricKeyEncrypted } = await signAndEncrypt(contract.symmetricKey, PEACHPGPPUBLICKEY)
  const [result, err] = await raiseDispute({
    contractId: contract.id,
    email,
    reason,
    message,
    symmetricKeyEncrypted,
  })
  if (result) {
    const updatedContract = {
      ...contract,
      disputeDate: new Date(Date.now()),
      disputeInitiator: account.publicKey,
    }
    const chat = getChat(contract.id)
    const autogeneratedMessages = initDisputeSystemMessages(chat.id, updatedContract)
    saveChat(contract.id, {
      messages: autogeneratedMessages,
    })
    return true
  }
  if (err) {
    error('Error', err)
    return false
  }
}
