import { configStore } from '../../../store/configStore'
import { account } from '../../../utils/account'
import { getChat, saveChat } from '../../../utils/chat'
import { initDisputeSystemMessages } from '../../../utils/chat/initDisputeSystemMessages'
import { error } from '../../../utils/log'
import { raiseDispute } from '../../../utils/peachAPI'
import { signAndEncrypt } from '../../../utils/pgp'

export const submitRaiseDispute = async (
  contract: Contract | undefined,
  reason: DisputeReason,
  email?: string,
  message?: string,
  // eslint-disable-next-line max-params
): Promise<[boolean, APIError | null]> => {
  if (!contract || !contract.symmetricKey) return [false, null]
  const { encrypted: symmetricKeyEncrypted } = await signAndEncrypt(
    contract.symmetricKey,
    configStore.getState().peachPGPPublicKey,
  )
  const [result, err] = await raiseDispute({
    contractId: contract.id,
    email,
    reason,
    message,
    symmetricKeyEncrypted,
  })
  if (result) {
    const updatedContract = {
      ...contract,
      disputeDate: new Date(Date.now()),
      disputeInitiator: account.publicKey,
      disputeReason: reason,
    }
    const chat = getChat(contract.id)
    const autogeneratedMessages = initDisputeSystemMessages(chat.id, updatedContract)
    saveChat(contract.id, {
      messages: autogeneratedMessages,
    })
    return [true, null]
  }
  if (err) {
    error('Error', err)
    return [false, err]
  }
  return [false, null]
}
