import { contract } from '../../../../tests/unit/data/contractData'
import { account } from '../../../utils/account'
import { submitRaiseDispute } from './submitRaiseDispute'

const raiseDisputeMock = jest.fn()
jest.mock('../../../utils/peachAPI', () => ({
  raiseDispute: (...args: unknown[]) => raiseDisputeMock(...args),
}))

// eslint-disable-next-line max-lines-per-function
describe('submitRaiseDispute', () => {
  const mockContract = { ...contract }
  it('should return [false, null] if contract is undefined', async () => {
    const [result, err] = await submitRaiseDispute({
      contract: undefined,
      reason: 'noPayment.buyer',
      symmetricKey: undefined,
    })
    expect(result).toBe(false)
    expect(err).toBe(null)
  })
  it('should return [false, null] if contract.symmetricKey is undefined', async () => {
    const [result, err] = await submitRaiseDispute({
      contract: mockContract,
      reason: 'noPayment.buyer',
      symmetricKey: undefined,
    })
    expect(result).toBe(false)
    expect(err).toBe(null)
  })
  it('should return [false, null] if raiseDispute returns no result and no error', async () => {
    raiseDisputeMock.mockResolvedValue([null, null])
    const [result, err] = await submitRaiseDispute({
      contract: mockContract,
      reason: 'noPayment.buyer',
      symmetricKey: undefined,
    })
    expect(result).toBe(false)
    expect(err).toBe(null)
  })
  it('should return [false, error] if raiseDispute returns no result and an error', async () => {
    raiseDisputeMock.mockResolvedValue([null, 'error'])
    const [result, err] = await submitRaiseDispute({
      contract: mockContract,
      reason: 'noPayment.buyer',
      symmetricKey: 'TODO',
    })
    expect(result).toBe(false)
    expect(err).toBe('error')
  })
  it('should return [true, null] if raiseDispute returns a result and no error', async () => {
    raiseDisputeMock.mockResolvedValue([{}, null])
    const [result, err] = await submitRaiseDispute({
      contract: mockContract,
      reason: 'noPayment.buyer',
      symmetricKey: 'TODO',
    })
    expect(result).toBe(true)
    expect(err).toBe(null)
  })
  it('should save chat with autogenerated messages', async () => {
    const disputeDate = new Date('2021-01-09')
    jest.spyOn(Date, 'now').mockImplementation(() => disputeDate.getTime())
    account.publicKey = 'buyer'
    const contractInDispute = {
      ...mockContract,
      disputeDate,
      disputeInitiator: account.publicKey,
      seller: {
        ...mockContract.seller,
        id: account.publicKey,
      },
      disputeReason: 'noPayment.seller',
    }
    raiseDisputeMock.mockResolvedValue([contractInDispute, null])

    const [result, err] = await submitRaiseDispute({
      contract: mockContract,
      reason: 'noPayment.seller',
      symmetricKey: 'TODO',
    })
    expect(result).toBe(true)
    expect(err).toBe(null)
  })
})
