type EuPaymentMethods =
  | "advcash"
  | "bankera"
  | "bizum"
  | "blik"
  | "fasterPayments"
  | "friends24"
  | "giftCard.steam"
  | "instantSepa"
  | "iris"
  | "keksPay"
  | "lydia"
  | "mbWay"
  | "mobilePay"
  | "n26"
  | "nationalTransferBG"
  | "nationalTransferCH"
  | "nationalTransferCZ"
  | "nationalTransferDK"
  | "nationalTransferHU"
  | "nationalTransferIS"
  | "nationalTransferNO"
  | "nationalTransferPL"
  | "nationalTransferRO"
  | "nationalTransferSE"
  | "nationalTransferTR"
  | "neteller"
  | "papara"
  | "payeer"
  | "paylib"
  | "paypal"
  | "paysera"
  | "perfectMoney"
  | "postePay"
  | "rebellion"
  | "revolut"
  | "satispay"
  | "sberbank"
  | "sepa"
  | "skrill"
  | "stp"
  | "straksbetaling"
  | "strike"
  | "swish"
  | "tinkoff"
  | "twint"
  | "vipps"
  | "westernUnion"
  | "wise"
  | "yooMoney";
type LatAmPaymentMethods =
  | "alias"
  | "bancolombia"
  | "bankTransferSuriname"
  | "cbu"
  | "chileBankDeposit"
  | "cvu"
  | "daviPlata"
  | "guatemalaBankDeposit"
  | "mercadoPago"
  | "nequi"
  | "paraguayBankTransfer"
  | "peruBankDeposit"
  | "pix"
  | "rappipay"
  | "sinpe"
  | "sinpeMovil"
  | "spei"
  | "tigoMoneyBolivia"
  | "tigoMoneyElSalvador"
  | "tigoMoneyGuatemala"
  | "tigoMoneyHonduras"
  | "moncash"
  | "natcash"
  | "tigoMoneyParaguay";
type AfricaPaymentMethods =
  | "accrue"
  | "airtelMoney"
  | "apaym"
  | "chippercash"
  | "djamo"
  | "eversend"
  | "kcbBankKenya"
  | "klasha"
  | "m-pesa"
  | "moov"
  | "mtn"
  | "nationalTransferNG"
  | "orangeMoney"
  | "payday"
  | "tigoPesa"
  | "wave"
  | "wirepay";

type OceaniaPaymentMethods = "payID" | "osko";
type AsiaPaymentMethods = "UPI" | "paytm" | "nationalTransferSG" | "payLah";
type northAmericaPaymentMethods =
  | "alias"
  | "bancolombia"
  | "bankTransferSuriname"
  | "cbu"
  | "chileBankDeposit"
  | "cvu"
  | "daviPlata"
  | "guatemalaBankDeposit"
  | "mercadoPago"
  | "nequi"
  | "paraguayBankTransfer"
  | "peruBankDeposit"
  | "pix"
  | "rappipay"
  | "sinpe"
  | "sinpeMovil"
  | "spei"
  | "tigoMoneyBolivia"
  | "tigoMoneyElSalvador"
  | "tigoMoneyGuatemala"
  | "tigoMoneyHonduras"
  | "moncash"
  | "natcash"
  | "tigoMoneyParaguay";

type BitcoinPaymentMethods = "liquid" | "lnurl";
type InternationalPaymentMethds =
  | "giftCard.amazon"
  | `giftCard.amazon.${PaymentMethodCountry}`;
type CashPaymentMethds = `cash.${string}`;

type PaymentMethod =
  | EuPaymentMethods
  | LatAmPaymentMethods
  | AfricaPaymentMethods
  | OceaniaPaymentMethods
  | AsiaPaymentMethods
  | InternationalPaymentMethds
  | BitcoinPaymentMethods
  | CashPaymentMethds;
