export { addProtocol } from './addProtocol'
export { callWhenInternet } from './callWhenInternet'
export { getLocalizedLink } from './getLocalizedLink'
export { goToShiftCrypto } from './goToShiftCrypto'
export { openAppLink } from './openAppLink'
