import { CurrencyType } from "../../../store/offerPreferenes/types";

const CURRENCY_MAP: Record<CurrencyType, Currency[]> = {
  europe: [
    "EUR",
    "CHF",
    "GBP",
    "SEK",
    "DKK",
    "BGN",
    "CZK",
    "HUF",
    "PLN",
    "RON",
    "ISK",
    "NOK",
    "TRY",
    "RUB",
  ],
  latinAmerica: [
    "ARS",
    "COP",
    "PEN",
    "MXN",
    "CLP",
    "PEN",
    "COP",
    "CRC",
    "BRL",
    "USD",
    "CAD",
    "UYU",
    "BRL",
    "PYG",
    "GTQ",
    "SRD",
    "BOB",
    "CLF",
    "CUC",
    "CUP",
    "DOP",
    "HNL",
    "PAB",
    "VEF",
    "VES",
  ],
  africa: ["USD", "XOF", "CDF", "NGN", "ZAR", "MAD", "KES", "TZS"],
  asia: [
    "KZT",
    "INR",
    "SGD",
    "TRY",
    "SAR",
    "PHP",
    "AED",
    "EGP",
    "JPY",
    "IDR",
    "MYR",
    "CNY",
    "PKR",
    "VND",
    "ILS",
    "RUB",
  ],
  oceania: ["AUD", "NZD"],
  other: ["USDT", "SAT"],
};

export const getCurrencyTypeFilter =
  (type: CurrencyType) => (currency: Currency) =>
    CURRENCY_MAP[type].includes(currency);
