import { shallow } from 'zustand/shallow'
import { useNavigation } from '../../../hooks'
import { DisputeWon } from '../components/DisputeWon'
import { usePopupStore } from '../../../store/usePopupStore'
import { getChat, saveChat } from '../../../utils/chat'
import { endDisputeSystemMessages } from '../../../utils/chat/endDisputeSystemMessages'
import { contractIdToHex, saveContract } from '../../../utils/contract'
import i18n from '../../../utils/i18n'
import { account } from '../../../utils/account'
import { useLocalContractStore } from '../../../store/useLocalContractStore'
import { getContract } from '../../../utils/peachAPI'
import { shouldShowDisputeResult } from '../../../utils/overlay'

export const useDisputeWonPopup = () => {
  const [setPopup, closePopup] = usePopupStore((state) => [state.setPopup, state.closePopup], shallow)
  const navigation = useNavigation()
  const updateContract = useLocalContractStore((state) => state.updateContract)

  const showDisputeWonPopup = async (contractId: string) => {
    const [contract] = await getContract({ contractId })
    if (!contract || !shouldShowDisputeResult(contract)) return
    const view = contract.buyer.id === account.publicKey ? 'buyer' : 'seller'
    if (contract.disputeWinner !== view) return
    const saveAcknowledgeMent = () => {
      saveContract({
        ...contract,
        disputeResolvedDate: new Date(),
      })
      updateContract(contract.id, {
        disputeResultAcknowledged: true,
        cancelConfirmationDismissed: view === 'buyer',
      })
      closePopup()
    }

    const goToChat = () => {
      saveAcknowledgeMent()
      navigation.navigate('contractChat', { contractId: contract.id })
    }

    const tradeId = contractIdToHex(contract.id)

    const chat = getChat(contract.id)
    const autogeneratedMessages = endDisputeSystemMessages(chat.id, contract)
    saveChat(contract.id, {
      messages: autogeneratedMessages,
    })
    setPopup({
      title: i18n('dispute.won'),
      level: 'SUCCESS',
      content: <DisputeWon tradeId={tradeId} />,
      visible: true,
      action2: {
        label: i18n('close'),
        icon: 'xSquare',
        callback: saveAcknowledgeMent,
      },
      action1: {
        label: i18n('goToChat'),
        icon: 'messageCircle',
        callback: goToChat,
      },
    })
  }
  return showDisputeWonPopup
}
