import { PaymentMethodInfo } from "../peach-api/src/@types/payment";
import { isCashTrade } from "./utils/paymentMethod/isCashTrade";

export const PAYMENTCATEGORIES: PaymentCategories = {
  bankTransfer: [
    "alias",
    "bancolombia",
    "guatemalaBankDeposit",
    "peruBankDeposit",
    "chileBankDeposit",
    "cbu",
    "cvu",
    "fasterPayments",
    "kcbBankKenya",
    "instantSepa",
    "sepa",
    "sinpe",
    "straksbetaling",
    "nationalTransferBG",
    "nationalTransferCH",
    "nationalTransferCZ",
    "nationalTransferDK",
    "nationalTransferHU",
    "nationalTransferIS",
    "nationalTransferNG",
    "nationalTransferNO",
    "nationalTransferPL",
    "nationalTransferRO",
    "nationalTransferSE",
    "nationalTransferSG",
    "nationalTransferTR",
    "paraguayBankTransfer",
  ],
  onlineWallet: [
    "accrue",
    "advcash",
    "airtelMoney",
    "apaym",
    "bankera",
    "blik",
    "chippercash",
    "daviPlata",
    "djamo",
    "eversend",
    "friends24",
    "klasha",
    "m-pesa",
    "mercadoPago",
    "moov",
    "mtn",
    "n26",
    "nequi",
    "neteller",
    "orangeMoney",
    "osko",
    "papara",
    "payday",
    "payeer",
    "payID",
    "payLah",
    "paypal",
    "paysera",
    "paytm",
    "perfectMoney",
    "pix",
    "revolut",
    "sinpeMovil",
    "skrill",
    "spei",
    "strike",
    "swish",
    "tigoMoneyBolivia",
    "tigoMoneyElSalvador",
    "tigoMoneyGuatemala",
    "tigoMoneyHonduras",
    "tigoMoneyParaguay",
    "tigoPesa",
    "twint",
    "UPI",
    "vipps",
    "wave",
    "westernUnion",
    "wirepay",
    "wise",
  ],
  giftCard: [
    "giftCard.steam",
    "giftCard.amazon",
    "giftCard.amazon.DE",
    "giftCard.amazon.FR",
    "giftCard.amazon.IT",
    "giftCard.amazon.ES",
    "giftCard.amazon.NL",
    "giftCard.amazon.UK",
    "giftCard.amazon.SE",
    "giftCard.amazon.PT",
  ],
  nationalOption: [
    "bizum",
    "iris",
    "keksPay",
    "lydia",
    "mbWay",
    "mobilePay",
    "paylib",
    "postePay",
    "rebellion",
    "satispay",
  ],
  cash: [],
  global: ["liquid", "lnurl"],
};

export const setPaymentMethods = (paymentMethodInfos: PaymentMethodInfo[]) => {
  PAYMENTCATEGORIES.cash = paymentMethodInfos
    .map(({ id }) => id)
    .filter(isCashTrade);
};
