import { Currency } from "../peach-api/src/@types/global";
import { PaymentMethodCountry } from "../peach-api/src/@types/offer";
import {
  PaymentMethod,
  PaymentMethodInfo,
} from "../peach-api/src/@types/payment";
import { uniqueArray } from "./utils/array/uniqueArray";
import { isCashTrade } from "./utils/paymentMethod/isCashTrade";

export let CURRENCIES: Currency[] = [
  "SAT",
  "EUR",
  "CHF",
  "USD",
  "GBP",
  "SEK",
  "DKK",
  "BGN",
  "CZK",
  "HUF",
  "PLN",
  "RON",
  "ISK",
  "NOK",
  "TRY",
  "USDT",
  "ARS",
  "COP",
  "PEN",
  "MXN",
  "CLP",
  "PEN",
  "COP",
  "XOF",
  "NGN",
  "CDF",
  "CRC",
  "BRL",
  "AUD",
  "ILS",
  "RSD",
  "CAD",
  "KZT",
  "INR",
  "SGD",
  "SAR",
  "PHP",
  "AED",
  "EGP",
  "JPY",
  "NZD",
  "MAD",
  "UAH",
  "UYU",
  "IDR",
  "MYR",
  "CNY",
  "PKR",
  "VND",
  "RUB",
  "BOB",
  "CLF",
  "CUC",
  "CUP",
  "DOP",
  "HNL",
  "PAB",
  "PYG",
  "VEF",
  "VES",
  "SRD",
  "TZS",
];

export let GIFTCARDCOUNTRIES: PaymentMethodCountry[] = [
  "DE",
  "FR",
  "IT",
  "ES",
  "NL",
  "UK",
  "SE",
  "FI",
  "PT",
];
export const NATIONALTRANSFERCOUNTRIES = [
  "BG",
  "CZ",
  "DK",
  "HU",
  "NO",
  "PL",
  "RO",
  "CH",
  "IS",
  "SE",
  "TR",
  "NG",
  "SG",
] as const;

const bankTransfer: PaymentMethod[] = [
  "alias",
  "bancolombia",
  "cbu",
  "cvu",
  "fasterPayments",
  "instantSepa",
  "sepa",
  "sinpe",
  "straksbetaling",
  "paraguayBankTransfer",
  "guatemalaBankDeposit",
  "chileBankDeposit",
  "peruBankDeposit",
  "kcbBankKenya",
  "bankTransferSuriname",
  ...NATIONALTRANSFERCOUNTRIES.map(
    (c) => `nationalTransfer${c}` satisfies PaymentMethod,
  ),
];
const onlineWallet: PaymentMethod[] = [
  "accrue",
  "advcash",
  "airtelMoney",
  "bankera",
  "blik",
  "chippercash",
  "daviPlata",
  "eversend",
  "friends24",
  "klasha",
  "m-pesa",
  "mobilePay",
  "moncash",
  "moov",
  "mtn",
  "natcash",
  "n26",
  "nequi",
  "neteller",
  "orangeMoney",
  "osko",
  "papara",
  "payday",
  "paypal",
  "paysera",
  "pix",
  "rappipay",
  "revolut",
  "sinpeMovil",
  "skrill",
  "strike",
  "swish",
  "tigoMoneyBolivia",
  "tigoMoneyElSalvador",
  "tigoMoneyGuatemala",
  "tigoMoneyHonduras",
  "tigoMoneyParaguay",
  "tigoPesa",
  "twint",
  "UPI",
  "vipps",
  "wave",
  "westernUnion",
  "wirepay",
  "wise",
  "djamo",
  "apaym",
  "payID",
  "payLah",
  "paytm",
  "perfectMoney",
  "payeer",
  "yooMoney",
  "mercadoPago",
  "stp",
  "spei",
];
const giftCard: PaymentMethod[] = [
  "giftCard.amazon",
  "giftCard.steam",
  ...GIFTCARDCOUNTRIES.map(
    (c) => `giftCard.amazon.${c}` satisfies PaymentMethod,
  ),
];
const nationalOption: PaymentMethod[] = [
  "bizum",
  "iris",
  "keksPay",
  "lydia",
  "mbWay",
  "mobilePay",
  "paylib",
  "postePay",
  "rebellion",
  "satispay",
  "tinkoff",
  "sberbank",
];
const other: PaymentMethod[] = ["liquid", "lnurl"];

type PaymentCategories = {
  [key in PaymentCategory]: PaymentMethod[];
};
export const PAYMENTCATEGORIES: PaymentCategories = {
  bankTransfer,
  onlineWallet,
  giftCard,
  nationalOption,
  cash: [],
  other,
};

export const setPaymentMethods = (paymentMethodInfos: PaymentMethodInfo[]) => {
  CURRENCIES = paymentMethodInfos
    .reduce((arr: Currency[], info) => arr.concat(info.currencies), [])
    .filter(uniqueArray);
  GIFTCARDCOUNTRIES = paymentMethodInfos
    .reduce(
      (arr: PaymentMethodCountry[], info) => arr.concat(info.countries || []),
      [],
    )
    .filter(uniqueArray);
  PAYMENTCATEGORIES.cash.push(
    ...paymentMethodInfos.map(({ id }) => id).filter(isCashTrade),
  );
};
