import { GIFTCARDCOUNTRIES, NATIONALTRANSFERCOUNTRIES } from '../../../../paymentMethods'
import { FormProps } from '../../../../views/addPaymentMethod/PaymentMethodForm'
import {
  Template1,
  Template10,
  Template11,
  Template12,
  Template13,
  Template14,
  Template15,
  Template16,
  Template17,
  Template18,
  Template19,
  Template2,
  Template20,
  Template21,
  Template22,
  Template3,
  Template4,
  Template5,
  Template6,
  Template7,
  Template8,
  Template9,
} from '../templates'
import { GiftCardAmazon } from './GiftCardAmazon'

type PaymentMethodFormsType = {
  [key in PaymentMethod]?: (props: FormProps) => JSX.Element
}

export const PaymentMethodForms: PaymentMethodFormsType = {
  accrue: Template19,
  advcash: Template2,
  airtelMoney: Template12,
  alias: Template16,
  bancolombia: Template17,
  bankera: Template13,
  bizum: Template3,
  blik: Template3,
  cbu: Template14,
  chippercash: Template18,
  cvu: Template15,
  eversend: Template18,
  fasterPayments: Template5,
  friends24: Template3,
  'giftCard.amazon': GiftCardAmazon,
  instantSepa: Template1,
  iris: Template3,
  keksPay: Template3,
  klasha: Template19,
  liquid: Template10,
  lnurl: Template11,
  lydia: Template3,
  mbWay: Template3,
  mercadoPago: Template13,
  mobilePay: Template3,
  moov: Template12,
  'm-pesa': Template12,
  mtn: Template12,
  n26: Template6,
  nationalTransferNG: Template21,
  nequi: Template3,
  neteller: Template4,
  orangeMoney: Template12,
  papara: Template3,
  payday: Template18,
  paylib: Template3,
  paypal: Template6,
  paysera: Template8,
  pix: Template22,
  postePay: Template20,
  rappipay: Template12,
  rebellion: Template19,
  revolut: Template6,
  satispay: Template3,
  sepa: Template1,
  sinpe: Template1,
  sinpeMovil: Template3,
  skrill: Template4,
  straksbetaling: Template7,
  swish: Template3,
  twint: Template3,
  vipps: Template3,
  wave: Template12,
  wirepay: Template19,
  wise: Template6,
}

GIFTCARDCOUNTRIES.forEach((c) => (PaymentMethodForms[`giftCard.amazon.${c}`] = GiftCardAmazon))
NATIONALTRANSFERCOUNTRIES.forEach((c) => (PaymentMethodForms[`nationalTransfer${c}`] = Template9))
