import {
  Template1,
  Template2,
  Template3,
  Template4,
  Template5,
  Template6,
  Template7,
  Template8,
  Template9,
} from '../templates'
import { GiftCardAmazon } from './GiftCardAmazon'
import { PaymentMethodForms } from './paymentMethodForms'

describe('paymentMethodForms', () => {
  it('should assign the correct template to each payment method', () => {
    expect(PaymentMethodForms).toStrictEqual({
      sepa: Template1,
      fasterPayments: Template5,
      instantSepa: Template1,
      paypal: Template6,
      revolut: Template6,
      vipps: Template3,
      advcash: Template2,
      blik: Template3,
      wise: Template6,
      twint: Template3,
      swish: Template3,
      satispay: Template3,
      mbWay: Template3,
      bizum: Template3,
      mobilePay: Template3,
      skrill: Template4,
      neteller: Template4,
      paysera: Template8,
      straksbetaling: Template7,
      keksPay: Template3,
      friends24: Template3,
      n26: Template3,
      paylib: Template3,
      lydia: Template3,
      verse: Template3,
      iris: Template3,
      'giftCard.amazon': GiftCardAmazon,
      'giftCard.amazon.DE': GiftCardAmazon,
      'giftCard.amazon.ES': GiftCardAmazon,
      'giftCard.amazon.FI': GiftCardAmazon,
      'giftCard.amazon.FR': GiftCardAmazon,
      'giftCard.amazon.IT': GiftCardAmazon,
      'giftCard.amazon.NL': GiftCardAmazon,
      'giftCard.amazon.SE': GiftCardAmazon,
      'giftCard.amazon.UK': GiftCardAmazon,
      nationalTransferBE: Template9,
      nationalTransferBG: Template9,
      nationalTransferCA: Template9,
      nationalTransferCH: Template9,
      nationalTransferCY: Template9,
      nationalTransferCZ: Template9,
      nationalTransferDE: Template9,
      nationalTransferDK: Template9,
      nationalTransferES: Template9,
      nationalTransferFI: Template9,
      nationalTransferFR: Template9,
      nationalTransferGB: Template9,
      nationalTransferGR: Template9,
      nationalTransferHU: Template9,
      nationalTransferIT: Template9,
      nationalTransferNL: Template9,
      nationalTransferNO: Template9,
      nationalTransferPL: Template9,
      nationalTransferPO: Template9,
      nationalTransferPT: Template9,
      nationalTransferRO: Template9,
      nationalTransferSE: Template9,
      nationalTransferSI: Template9,
      nationalTransferUS: Template9,
    })
  })
})
